server:
  address:     ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level : "all"
  stdout: true


# Database.
database:
  logger:
    level:   "all"
    stdout:  true

  default:
    link:   "mysql:w1p4g7lzkq4l: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@tcp(9eo6z8dgr0s1.umy_apps-east-3.psdb.cloud:3306)/my_app"
    debug:  true
