// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Application is the golang structure of table application for DAO operations like Where/Data.
type Application struct {
	g.Meta    `orm:"table:application, do:true"`
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
	IsDeleted interface{} //
	Name      interface{} // 应用名称
	Type      interface{} // 应用类型
	Icon      interface{} // 应用图标
	Desc      interface{} // 应用描述
	DownCount interface{} // 下载次数
	Id        interface{} //
}
