// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// File is the golang structure of table file for DAO operations like Where/Data.
type File struct {
	g.Meta    `orm:"table:file, do:true"`
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
	IsDeleted interface{} //
	Md5       interface{} // 文件MD5
	Sha1      interface{} // 文件 SHA1
	Name      interface{} // 文件名称
	DownUrl   interface{} // 下载地址
	DownCount interface{} // 下载次数
	VersionId interface{} // 版本 ID
	CertId    interface{} // 证书 ID
	Id        interface{} //
}
