// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Logger is the golang structure of table logger for DAO operations like Where/Data.
type Logger struct {
	g.Meta            `orm:"table:logger, do:true"`
	CreatedAt         *gtime.Time //
	UpdatedAt         *gtime.Time //
	IsDeleted         interface{} //
	VersionId         interface{} // 版本 ID
	OperationDesc     interface{} // 操作描述
	OperationUser     interface{} // 操作用户
	OperationUserName interface{} // 操作用户名
	RemoteIp          interface{} // 操作 IP
	Content           interface{} // 日志内容
	Id                interface{} //
}
