// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// PackageJson is the golang structure of table package_json for DAO operations like Where/Data.
type PackageJson struct {
	g.Meta    `orm:"table:package_json, do:true"`
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
	IsDeleted interface{} //
	VersionId interface{} // 版本 ID
	Info      interface{} // erpxa文件信息
	Type      interface{} // 应用类型
	Id        interface{} //
}
