// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Tag is the golang structure of table tag for DAO operations like Where/Data.
type Tag struct {
	g.Meta    `orm:"table:tag, do:true"`
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
	IsDeleted interface{} //
	Name      interface{} // 标签名称
	Type      interface{} // 应用类型
	Id        interface{} //
}
