// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// UserRole is the golang structure of table user_role for DAO operations like Where/Data.
type UserRole struct {
	g.Meta    `orm:"table:user_role, do:true"`
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
	IsDeleted interface{} //
	UserEmail interface{} // 用户ID
	RoleName  interface{} // 角色名称
	Id        interface{} //
}
