// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Version is the golang structure of table version for DAO operations like Where/Data.
type Version struct {
	g.Meta      `orm:"table:version, do:true"`
	CreatedAt   *gtime.Time //
	UpdatedAt   *gtime.Time //
	IsDeleted   interface{} //
	Tag         interface{} // 应用标签
	AppId       interface{} // 应用 ID
	Status      interface{} // 应用状态
	Source      interface{} // 应用来源
	UserId      interface{} // 用户 ID
	UserName    interface{} // 用户名
	Version     interface{} // 应用版本
	Instruction interface{} // 应用使用说明
	ReleaseNote interface{} // 应用更新说明
	ApproveDesc interface{} // 审批意见
	Id          interface{} //
}
