// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"myapp/internal/dao/internal"
)

// internalCertDao is internal type for wrapping internal DAO implements.
type internalCertDao = *internal.CertDao

// certDao is the data access object for table cert.
// You can define custom methods on it to extend its functionality as you wish.
type certDao struct {
	internalCertDao
}

var (
	// Cert is globally public accessible object for table cert operations.
	Cert = certDao{
		internal.NewCertDao(),
	}
)

// Fill with you ideas below.
