// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"myapp/internal/dao/internal"
)

// internalLoggerDao is internal type for wrapping internal DAO implements.
type internalLoggerDao = *internal.LoggerDao

// loggerDao is the data access object for table logger.
// You can define custom methods on it to extend its functionality as you wish.
type loggerDao struct {
	internalLoggerDao
}

var (
	// Logger is globally public accessible object for table logger operations.
	Logger = loggerDao{
		internal.NewLoggerDao(),
	}
)

// Fill with you ideas below.
