// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"myapp/internal/dao/internal"
)

// internalPackageJsonDao is internal type for wrapping internal DAO implements.
type internalPackageJsonDao = *internal.PackageJsonDao

// packageJsonDao is the data access object for table package_json.
// You can define custom methods on it to extend its functionality as you wish.
type packageJsonDao struct {
	internalPackageJsonDao
}

var (
	// PackageJson is globally public accessible object for table package_json operations.
	PackageJson = packageJsonDao{
		internal.NewPackageJsonDao(),
	}
)

// Fill with you ideas below.
