// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Application is the golang structure for table application.
type Application struct {
	CreatedAt *gtime.Time `json:"createdAt" description:""`
	UpdatedAt *gtime.Time `json:"updatedAt" description:""`
	IsDeleted int         `json:"isDeleted" description:""`
	Name      string      `json:"name"      description:"应用名称"`
	Type      string      `json:"type"      description:"应用类型"`
	Icon      string      `json:"icon"      description:"应用图标"`
	Desc      string      `json:"desc"      description:"应用描述"`
	DownCount int         `json:"downCount" description:"下载次数"`
	Id        int         `json:"id"        description:""`
}
