// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Logger is the golang structure for table logger.
type Logger struct {
	CreatedAt         *gtime.Time `json:"createdAt"         description:""`
	UpdatedAt         *gtime.Time `json:"updatedAt"         description:""`
	IsDeleted         int         `json:"isDeleted"         description:""`
	VersionId         string      `json:"versionId"         description:"版本 ID"`
	OperationDesc     string      `json:"operationDesc"     description:"操作描述"`
	OperationUser     string      `json:"operationUser"     description:"操作用户"`
	OperationUserName string      `json:"operationUserName" description:"操作用户名"`
	RemoteIp          string      `json:"remoteIp"          description:"操作 IP"`
	Content           string      `json:"content"           description:"日志内容"`
	Id                int         `json:"id"                description:""`
}
