// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// PackageJson is the golang structure for table package_json.
type PackageJson struct {
	CreatedAt *gtime.Time `json:"createdAt" description:""`
	UpdatedAt *gtime.Time `json:"updatedAt" description:""`
	IsDeleted int         `json:"isDeleted" description:""`
	VersionId string      `json:"versionId" description:"版本 ID"`
	Info      string      `json:"info"      description:"erpxa文件信息"`
	Type      string      `json:"type"      description:"应用类型"`
	Id        int         `json:"id"        description:""`
}
