// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Tag is the golang structure for table tag.
type Tag struct {
	CreatedAt *gtime.Time `json:"createdAt" description:""`
	UpdatedAt *gtime.Time `json:"updatedAt" description:""`
	IsDeleted int         `json:"isDeleted" description:""`
	Name      string      `json:"name"      description:"标签名称"`
	Type      string      `json:"type"      description:"应用类型"`
	Id        int         `json:"id"        description:""`
}
