// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure for table user.
type User struct {
	CreatedAt *gtime.Time `json:"createdAt" description:""`
	UpdatedAt *gtime.Time `json:"updatedAt" description:""`
	IsDeleted int         `json:"isDeleted" description:""`
	Username  string      `json:"username"  description:""`
	Email     string      `json:"email"     description:""`
	Password  string      `json:"password"  description:""`
	Active    int         `json:"active"    description:""`
	Id        int         `json:"id"        description:""`
}
