// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Version is the golang structure for table version.
type Version struct {
	CreatedAt   *gtime.Time `json:"createdAt"   description:""`
	UpdatedAt   *gtime.Time `json:"updatedAt"   description:""`
	IsDeleted   int         `json:"isDeleted"   description:""`
	Tag         string      `json:"tag"         description:"应用标签"`
	AppId       string      `json:"appId"       description:"应用 ID"`
	Status      string      `json:"status"      description:"应用状态"`
	Source      string      `json:"source"      description:"应用来源"`
	UserId      string      `json:"userId"      description:"用户 ID"`
	UserName    string      `json:"userName"    description:"用户名"`
	Version     string      `json:"version"     description:"应用版本"`
	Instruction string      `json:"instruction" description:"应用使用说明"`
	ReleaseNote string      `json:"releaseNote" description:"应用更新说明"`
	ApproveDesc string      `json:"approveDesc" description:"审批意见"`
	Id          int         `json:"id"          description:""`
}
